# Generated by Django 4.2.2 on 2023-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivoPDF",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("archivo", models.FileField(upload_to="pdf/")),
            ],
        ),
    ]
