# Generated by Django 4.2.1 on 2023-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='archivo',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
